### ISSUE TITLE
Monsters are not real

### ISSUE THREAD

**Issue by ferrouswheel** [Hokioi/datasciencecoursera#1]
This is New Zealand propaganda.

Monsters are just figments of my imagination!

**Comment by ferrouswheel** [comment]
I clearly have no idea what I am doing.

**Comment by Hokioi** [comment]
Clearly this commenter is a fake person. All reasonable people know that monsters are entirely real and that people are merely monsters wearing human costumes.

**Comment by Hokioi** [comment]
So there.

**Comment by ferrouswheel** [comment]
But...

![](https://media.giphy.com/media/3ohc1fcSMX3dd8fzq0/giphy.gif)
